var playerArray = [
    'img/player/playerhx.png',
    'img/player/playerhxy.png',
    'img/player/playerwhy.png',
    'img/player/playerlyx.png',
    'img/player/playerljh.png',
    'img/player/playerlfc.png',
    'img/player/playerlw.png',
    'img/player/playerwxj.png',
    'img/player/playerhc.png',
    'img/player/playerxf.png',
    'img/player/playerlsh.png',
    'img/player/playerhpt.png',
    'img/player/playerlh.png',
    'img/player/playerxr.png',
    'img/player/playerhj.png',
];
var playerWineArray = [
    'img/playerWine/playerhx.png',
    'img/playerWine/playerhxy.png',
    'img/playerWine/playerwhy.png',
    'img/playerWine/playerlyx.png',
    'img/playerWine/playerljh.png',
    'img/playerWine/playerlfc.png',
    'img/playerWine/playerlw.png',
    'img/playerWine/playerwxj.png',
    'img/playerWine/playerhc.png',
    'img/playerWine/playerxf.png',
    'img/playerWine/playerlsh.png',
    'img/playerWine/playerhpt.png',
    'img/playerWine/playerlh.png',
    'img/playerWine/playerxr.png',
    'img/playerWine/playerhj.png',
];
var playerIconArray = [
    'img/playerIcon/playerhx.png',
    'img/playerIcon/playerhxy.png',
    'img/playerIcon/playerwhy.png',
    'img/playerIcon/playerlyx.png',
    'img/playerIcon/playerljh.png',
    'img/playerIcon/playerlfc.png',
    'img/playerIcon/playerlw.png',
    'img/playerIcon/playerwxj.png',
    'img/playerIcon/playerhc.png',
    'img/playerIcon/playerxf.png',
    'img/playerIcon/playerlsh.png',
    'img/playerIcon/playerhpt.png?v=3',
    'img/playerIcon/playerlh.png',
    'img/playerIcon/playerxr.png',
    'img/playerIcon/playerhj.png',
];
var playerNameArray = [
    '黄潇',
    '黄晓阳',
    '王皓宇',
    '刘宇雄',
    '李家豪',
    '梁富超',
    '刘伟',
    '王玺君',
    '韩超',
    '薛峰',
    '李舜浩',
    '胡平涛',
    '李晗',
    '谢睿',
    '黄佳',
];
var playerStyleArray = [
    { 'width': '88%', 'bottom': '-3%', 'left': '-12%', 'transform': 'scaleX(1)' },
    { 'width': '112%', 'bottom': '-30%', 'left': '-36%', 'transform': 'scaleX(1)' },
    { 'width': '112%', 'bottom': '-12%', 'left': '-8%', 'transform': 'scaleX(1)' },
    { 'width': '94%', 'bottom': '-13%', 'left': '-24%', 'transform': 'scaleX(1)' },
    { 'width': '96%', 'bottom': '-14%', 'left': '-28%', 'transform': 'scaleX(1)' },
    { 'width': '116%', 'bottom': '-29%', 'left': '-43%', 'transform': 'scaleX(1)' },
    { 'width': '107%', 'bottom': '-16%', 'left': '-41%', 'transform': 'scaleX(1)' },
    { 'width': '103%', 'bottom': '-24%', 'left': '-24%', 'transform': 'scaleX(1)' },
    { 'width': '93%', 'bottom': '-16%', 'left': '-5%', 'transform': 'scaleX(1)' },
    { 'width': '97%', 'bottom': '-15%', 'left': '-36%', 'transform': 'scaleX(1)' },
    { 'width': '114%', 'bottom': '-15%', 'left': '-31%', 'transform': 'scaleX(1)' },
    { 'width': '118%', 'bottom': '-23%', 'left': '-37%', 'transform': 'scaleX(1)' },
    { 'width': '113%', 'bottom': '-29%', 'left': '-31%', 'transform': 'scaleX(1)' },
    { 'width': '107%', 'bottom': '-27%', 'left': '-37%', 'transform': 'scaleX(1)' },
    { 'width': '107%', 'bottom': '-20%', 'left': '-37%', 'transform': 'scaleX(1)' },
];
var playerNameEArray = [
    'Shakira Huang',
    'Casper Huang',
    'Sam Wang',
    'Krian Liu',
    'Howard Lee',
    'Andrew Leung',
    'Dennis Liu',
    'Edison Wang',
    'Matthew Han',
    'Ryan Xue',
    'Dino Lee',
    'Tao Hu',
    'Eddie Lee',
    'Ryan Xie',
    'Fly Huang',
];
var playerFormulaTitleArray = [
    'Warrior',
    '知更鸟',
    'Rock Hammer',
    '闲茶',
    'Neverland',
    'The Wind and Waves',
    '永无止境',
    '传世·蝠',
    '般若',
    'The 85th Day',
    'Original Intention',
    'Back In Time',
    'Into The Wild',
    'The Underdog',
    'Straight To The Beach',
];
var playerFormulaArray = [
    '灵感配方：<br/>50ml 百加得8年朗姆酒<br/>12ml 比格蕾苦橙利口酒<br/>12ml 圣哲曼接骨木花利口酒<br/>12ml 红酒酸<br/>3滴 肉桂苦精',
    '灵感配方：<br/>45ml 百加得8年朗姆酒<br/>30ml 红石榴果露<br/>2滴 芹菜苦精<br/>1 / 2吧勺 班兰叶糖浆<br/>10滴鱼酱<br/>若干片 海苔',
    '灵感配方：<br/>60ml 百加得8年朗姆酒<br/>20ml 焦糖酱<br/>2.5ml 苦艾酒<br/>7ml 新鲜姜汁<br/>10ml 新鲜酸橙汁<br/>1撮 零陵香豆',
    '灵感配方：<br/>45ml 百加得白朗姆<br/>20ml 南方乌龙茶浸泡金酒<br/>25ml 法国廊酒<br/>10ml 新鲜黄柠汁<br/>5片 薄荷叶',
    '灵感配方：<br/>45ml 百加得8年朗姆酒<br/>15ml榛子利口酒<br/>10ml柠檬汁<br/>10ml枫糖浆<br/>1 / 2 吧勺 黄芥末<br/>1份 柠檬皮<br/>',
    '灵感配方：<br/>50ml 百加得白朗姆<br/>10ml 绿荨麻酒<br/>70ml 菠萝汁<br/>3g 香菜<br/>20ml 柠檬汁<br/>20ml 甘露糖浆 <br/>',
    '灵感配方：<br/>50ml 百加得8年朗姆酒<br/>15ml 法国廊酒<br/>20ml 新鲜甜菜根汁<br/>15ml 新鲜柠檬汁<br/>5ml 蔗糖浆<br/>',
    '灵感配方：<br/>60ml 百加得金朗姆<br/>15ml 百香果果汁<br/>7ml 白酒醋<br/>13ml 自制五味子糖浆<br/>1ml 蛋清<br/>',
    '灵感配方：<br/>45ml 百加得8年朗姆酒<br/>20ml 白酒<br/>1个 百香果<br/>30ml 玫瑰糖浆<br/>5个 迷迭香',
    '灵感配方：<br/>60ml 百加得白朗姆<br/>30ml 菠萝汁<br/>15ml 纯蔗糖<br/>10ml 马利宝椰子朗姆酒<br/>10ml 新鲜酸橙汁<br/>10ml 意式浓缩咖啡',
    '灵感配方：<br/>45ml 百加得8年朗姆酒<br/>15ml 姜味利口酒<br/>20ml 山楂水<br/>7.5ml 红糖糖浆<br/>1长匙 艾雷岛威士忌',
    '灵感配方：<br/>45ml 百加得8年朗姆酒<br/>30ml 新鲜西柚汁<br/>15ml 意式咖啡利口酒<br/>5ml 枫叶糖浆<br/>30ml 健力士黑啤',
    '灵感配方：<br/>50ml 百加得白朗姆酒<br/>40ml 新鲜菠萝汁<br/>7.5ml 柠檬香草糖浆<br/>2滴 山苍子油<br/>1滴 安哥斯特拉苦酒<br/>',
    '灵感配方：<br/>45ml 百加得8年朗姆酒<br/>15ml 中国花雕酒<br/>10ml龙舌兰糖浆<br/>30ml柠檬汁<br/>3ml 苦艾酒',
    '灵感配方：<br/>60ml 百加得超级白朗姆<br/>15ml 新鲜青柠汁<br/>10ml 椰子糖浆<br/>2.5ml 路萨朵野樱桃<br/>30ml 椰子水<br/>1ml 自制海盐水（4:1）',
];
var playerInfoArray = [
    '“Warrior”的灵感来自于黄潇非常喜欢的一部拳击主题电影《勇士》。当她初入调酒师这一行时，就决心要调制一杯拥有勇士精神的酒，将勇者的无畏传递给每一位品酒人。酒如人生，在这杯“Warrior”里有快乐之甜，有艰辛之酸，也有困厄之苦。面对世间冷暖，她以这杯酒来鼓励人们成为生活中的勇士，强大自己内心，为人生放手一搏。',
    '知更鸟是一种候鸟，年复一年地沿着既定路线迁徙。每年3月，当明媚的春天到来之时，它们一路向北。黄晓阳的这杯“知更鸟”就好像它们的“长途旅行”，起初香兰和西芹的清新似如出发前的新奇，再是石榴甜酒，象征着迁徙之路上的愉悦，最后鱼酱的甘甜和百加得8年朗姆酒的醇厚则是即将到达目的地的欣喜。喝一杯“知更鸟”，仿佛跟随知更鸟体验了一场盛大的迁徙。',
    '这杯“Rock Hammer”的灵感来自于电影《肖申克的救赎》，影片主人公安迪身陷监狱中，但拥有坚定信念的他从未放弃逃出去的希望。不管环境如何艰难，最后他用一把石锤，获得了自由，改变了命运。当调酒师Sam再一次看这部电影时，也从中获得了对调酒的新理解。身为一名调酒师，每天会遇见许多人，他们都有着自己不同的心事，Sam希望他调制出的“Rock Hammer”可以和影片中安迪的石锤一样，给予大家力量，用坚忍不拔的信念帮助人们打破困境。',
    '这杯“闲茶”装满着刘宇雄儿时对家乡的记忆，离家多年的他时时牵挂着家乡的亲人们。刘宇雄常会回忆起曾经奶奶为他泡茶的画面。长大后，每每喝起茶，那茶水回甘与苦涩总能将记忆带回过去，那些和奶奶的日子。茶与酒的美妙碰撞，也让回忆发光。',
    '这杯“Neverland”的灵感诞生于在柏林的早餐时间。那时，李家豪正好在柏林观看2017年的百加得传世鸡尾酒大赛。在柏林观赛的这期间，他感受到了从未有过的愉悦和放松。他在这些短暂的轻松时光中发现了一些以前难以感受到的微小而简单的快乐，这感觉就好像来自于久违的童年。所以，这杯“Neverland”就是带着这样的爱与情感，展现在大家眼前。',
    '梁富超在刚成为调酒师的时候，曾一度感觉到迷茫。有一次，当他看到当时的酒吧经理创作了一款用香菜制作的鸡尾酒，从而对调酒师这个职业产生了浓厚的兴趣。那位酒吧经理对他产生了巨大的影响，也让他的职业生涯发生了改变。现在，虽然那个酒吧经理已经离开了调酒行业。但梁富超带着他和自己对调酒行业的热爱，走到了今天。并用这杯“The Wind and Waves”怀念这位伙伴。',
    '这杯“永无止尽”的灵感来源于宫崎骏的《千与千寻》，少女千寻经历了万般磨难，最后找回了失去的父母和自己的名字。她辛苦追寻的过程好像唐·法昆多·百加得先生从古巴离开，但却一心想要回到古巴一样。刘伟想用这杯“永无止尽”告诉大家，永不放弃终究会成功，向上的道路永无止尽。',
    '调酒师就好像百加得的标志“蝙蝠”：夜间出没，在深夜聆听每一个人藏在酒里的故事；隐于清晨，默默承受着熬夜和亚健康的身体状况。出生于医药世家的王玺君不仅坚持着成为一名专业调酒师的梦想，还将草药知识完美融合进鸡尾酒。在他这次的作品里，用五味子制作成糖浆，补气凝神的同时，还能让喝酒的人得到一夜好眠。',
    '调酒师每一天都要为客人调制很多的酒，但很多人却从未给家人好好调制一杯鸡尾酒。有时虽有歉疚，但总会给自己一个安慰的理由：是为了让家人有更好的生活。于是很多事情就这样被忽略了。韩超将这杯名为“般若”的鸡尾酒，献给家人，也提醒正在拼搏着的人们，忙碌之余，不要忘记关心身边爱你的人们。',
    'The 85th Day的灵感来自于海明威的《老人与海》，老人在历经84天磨难无功而返之后，终于在第85天钓到一条大马林鱼。在这之中，不管过程如何艰难，他从未放弃薛峰在鸡尾酒中特别加入意式浓缩咖啡，以象征苦难；椰子利口酒和菠萝汁又在这苦中带来一缕甜。这杯酒在诉说着一个关于坚韧的故事：“一个人可以被摧毁，但绝不可能被打败。”',
    '纽约Milk & Honey的Sam Ross在2005年创作了经典鸡尾酒Penicillin，李舜浩向这杯经典鸡尾酒致敬，并创新地加入了传统的中国食材红糖和山楂。他的这杯名为Original Intention的鸡尾酒不仅寓意着唐·法昆多·百加得先生对朗姆酒品质精益求精的初心，还有李舜浩用心把每一杯鸡尾酒做到最好的初心。所有的初心融合在一起，成就了这杯Original Intention。',
    'Back In Time这杯鸡尾酒的灵感来自于1900年为庆祝古巴战争胜利而诞生的经典鸡尾酒“自由古巴”。百加得不被驯服、坚持创造的精神让这杯酒更富有传奇色彩。胡平涛想用这杯“Back In Time”告诉所有调酒师：不论你身在何处，都别忘了过去所有的胜利来之不易。同时也激励调酒师们，坚持自我，逆流而上，勇创经典！',
    'Into The Wild，是一款热情、积极、充满力量的TIKI风格鸡尾酒。它的灵感来源于百加得所蕴含的自由、色彩和激情的精神，同时还传承了唐·法昆多·百加得·马索先生对朗姆酒孜孜不倦的追求。',
    '“The Underdog”的灵感来自于那些曾被轻视的人们，他们承受着别人的冷眼，不被信任，不被看好。在成为调酒师的道路上，Ryan也曾经历过同样的遭遇，最初没有人相信他能够成为一名出色的调酒师。而Ryan无惧他人的眼光，坚守着自己对调酒的热爱。现在，他用这样一杯“The Underdog”证明了自己。',
    '“Straight To The Beach”的灵感来自于两款经典鸡尾酒“海明威大吉利”和“椰林飘香”，这两款鸡尾酒都是以朗姆酒为基酒，并极佳地彰显了朗姆酒的本味特色。Fly想要用这杯“Straight To The Beach”来诠释更真实的朗姆酒之味，续写百加得朗姆酒的经典传奇。',
];
var partyAreaArray = [
    '上海赛区',
    '北京赛区',
    '成都赛区',
    '深圳赛区',
    '广州赛区',
];
var partyDateArray = [
    '1月07日(周日)',
    '1月14日(周日)',
    '1月21日(周日)',
    '1月27日(周六)',
    '1月28日(周日)',
];
var partyNameArray = [
    'Above the Globe',
    'Bora bora',
    'the alcohol<br/>business co,.ltd<br/>(T.A.B.CLUB)',
    'Ciao Amici Whisky<br/>and Cocktails',
    "Guu's Cigar& Whisky <br/>Lounge",
];
var partyAddArray = [
    '上海市北京西路1013号7楼',
    '北京朝阳区青年路29号院3号楼102',
    '四川省成都市锦江区滨江东路136号',
    '深圳市海云路与海天二路交口软件产业基地6栋1层',
    '广州市海珠区艺景路振华商务中心901',
];